In [1]:
#loading data

import pandas as pd

model = pd.read_csv("results/predictions_with_details_full_reduced_normal.csv")

In [2]:
pathogenic_model = model[model['Predicted_Label_Display'] == 'Pathogenic']
pathogenic_model.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
3063,1162160250,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470034,SLC19A2,-,CA,CA:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.954196,Pathogenic,False
3280,1187119462,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALL,snv,169485653,SLC19A2,G,T,A:0.00014:1:Korea4K|A:0.00018:14:TOMMO,stop_gained;coding_sequence_variant;synonymous...,-2,0.909167,Pathogenic,False
3519,1213206212,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468665,SLC19A2,AT,-,-:0.0000029:4:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.988252,Pathogenic,False
4912,1372261451,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486642,SLC19A2,C,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.446822,Pathogenic,True
4960,1379204044,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468243,SLC19A2,A,-,NaN,frameshift_variant;coding_sequence_variant,-2,0.989858,Pathogenic,False
5416,1424601135,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486653,SLC19A2,C,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.374474,Pathogenic,True
5481,1430840234,MDVPGPVSRRAAAAAATVLLRTARVRREC,snv,169485678,SLC19A2,C,T,T:0.0000015:2:GnomAD_exomes|A:0.0000067:1:Gnom...,missense_variant;coding_sequence_variant;stop_...,-2,0.822899,Pathogenic,False
6106,1553213506,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFPAS...,del,169485637,SLC19A2,C,-,-:0.03163:329:GoESP,frameshift_variant;coding_sequence_variant,-2,0.992316,Pathogenic,False
6107,1553213508,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFSPAS...,del,169485641,SLC19A2,G,-,-:0.0238:256:GoESP,frameshift_variant;coding_sequence_variant,-2,0.972196,Pathogenic,False
6135,1557889112,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169469971,SLC19A2,G,-,-:0.000003:2:GnomAD_exomes|-:0.000004:1:TOPMED...,frameshift_variant;coding_sequence_variant,-2,0.995041,Pathogenic,False
7026,1658076788,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468143,SLC19A2,C,-,-:0.000004:1:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.974144,Pathogenic,False
7027,1658076868,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468145,SLC19A2,-,TGTGTAG,TGTGTAG:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.917680,Pathogenic,False
7086,1658095371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468752,SLC19A2,A,-,-:0.000008:2:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.992660,Pathogenic,False
7090,1658096725,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468795,SLC19A2,A,-,-:0.0000014:2:GnomAD_exomes|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.990674,Pathogenic,False
7094,1658097604,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468813,SLC19A2,-,A,AAA:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.993576,Pathogenic,False
7220,1658132918,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470100,SLC19A2,C,T,T:0.:0:ALFA,coding_sequence_variant;stop_gained,-2,0.826126,Pathogenic,False
7221,1658133007,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470101,SLC19A2,C,T,A:0.000002:1:GnomAD_exomes|T:0.:0:ALFA,coding_sequence_variant;stop_gained;missense_v...,-2,0.791357,Pathogenic,False
7739,1658264691,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474439,SLC19A2,A,C,C:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.480439,Pathogenic,True
7742,1658264969,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474449,SLC19A2,G,C,T:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.501431,Pathogenic,True
7743,1658264969,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474449,SLC19A2,G,T,T:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.395839,Pathogenic,True
8067,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.554198,Pathogenic,False
8100,1658355778,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477646,SLC19A2,-,C,C:0.000004:1:TOPMED|CCCCC:0.:0:ALFA,coding_sequence_variant;intron_variant;framesh...,-2,0.999482,Pathogenic,False
8262,1658385619,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478854,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-2,0.360893,Pathogenic,True
8974,1658538909,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485565,SLC19A2,C,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-2,0.999729,Pathogenic,False
8994,1658549091,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485776,SLC19A2,GAGGG,G,G:0.:0:ALFA,5_prime_UTR_variant,-2,0.990593,Pathogenic,False
9000,1658551595,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485789,SLC19A2,CCGGCC,CC,CC:0.:0:ALFA,5_prime_UTR_variant,-2,0.987875,Pathogenic,False
9145,1658582941,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169486663,SLC19A2,GTTTATAGTT,GTT,-:0.000008:2:TOPMED|GTT:0.000094:1:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.508521,Pathogenic,True
9354,186203570,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486682,SLC19A2,G,T,A:0.0002:1:1000Genomes|A:0.000156:1:1000Genome...,2KB_upstream_variant;upstream_transcript_variant,-2,0.345955,Pathogenic,True
9495,2101773099,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468113,SLC19A2,G,A,T:0.000002:1:GnomAD_exomes,missense_variant;stop_gained;coding_sequence_v...,-2,0.897029,Pathogenic,False
9497,2101773237,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468224,SLC19A2,C,A,A:0.00001:1:TOMMO,stop_gained;coding_sequence_variant,-2,0.958755,Pathogenic,False
9715,2101788568,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486638,SLC19A2,A,T,T:0.000312:2:1000Genomes_30X|T:0.000007:1:Gnom...,2KB_upstream_variant;upstream_transcript_variant,-2,0.430640,Pathogenic,True
9966,2526234346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468152,SLC19A2,CAATTAGAGTGAGCA,CA,-:0.0000043:6:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.941371,Pathogenic,False
10053,2526235999,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468658,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.981076,Pathogenic,False
10061,2526236130,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468700,SLC19A2,G,-,-:0.00001:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.983949,Pathogenic,False
10064,2526236154,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468706,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.981565,Pathogenic,False
10072,2526236236,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468728,SLC19A2,-,C,C:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.962662,Pathogenic,False
10074,2526236253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468730,SLC19A2,-,TGCAGCA,TGCAGCA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.985133,Pathogenic,False
10075,2526236267,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468732,SLC19A2,-,CAGGAGAG,CAGGAGAG:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant;stop_gained,-2,0.993707,Pathogenic,False
10079,2526236348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468759,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.986286,Pathogenic,False
10083,2526236371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468770,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.991244,Pathogenic,False
10084,2526236447,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468791,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.990452,Pathogenic,False
10085,2526236453,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468791,SLC19A2,GACCAG,G,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.993027,Pathogenic,False
10087,2526236505,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468797,SLC19A2,-,TT,TT:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.960654,Pathogenic,False
10223,2526240071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470079,SLC19A2,AG,-,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.973644,Pathogenic,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.885114,Pathogenic,False
10401,2526255842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477167,SLC19A2,G,-,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.646674,Pathogenic,False
10424,2526256167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477297,SLC19A2,-,T,T:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.767029,Pathogenic,False
10428,2526256643,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477335,SLC19A2,AGGTAAAAACCAGG,AGG,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.988445,Pathogenic,False
10439,2526256896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477403,SLC19A2,GCGACCAGCCTGCCACTG,G,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.992142,Pathogenic,False
10440,2526256902,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477403,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.992248,Pathogenic,False

In [9]:
pathogenic_old_model.iloc[50:100]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
9149,1658583425,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486691,SLC19A2,C,A,A:0.000007:1:GnomAD_genomes|A:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.625408,Pathogenic,True
9156,1658584605,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486761,SLC19A2,T,G,G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.666226,Pathogenic,True
9158,1658584791,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486779,SLC19A2,C,T,T:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.744228,Pathogenic,True
9333,184529626,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474445,SLC19A2,T,G,C:0.00016:1:1000Genomes_30X|T:0.4:4:SGDP_PRJ|C...,intron_variant,-2,0.447955,Pathogenic,True
9354,186203570,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486682,SLC19A2,G,T,A:0.0002:1:1000Genomes|A:0.000156:1:1000Genome...,2KB_upstream_variant;upstream_transcript_variant,-2,0.681564,Pathogenic,True
9495,2101773099,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468113,SLC19A2,G,A,T:0.000002:1:GnomAD_exomes,missense_variant;stop_gained;coding_sequence_v...,-2,0.997194,Pathogenic,False
9497,2101773237,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468224,SLC19A2,C,A,A:0.00001:1:TOMMO,stop_gained;coding_sequence_variant,-2,0.999594,Pathogenic,False
9568,2101778811,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474351,SLC19A2,G,C,C:0.00001:1:TOMMO,intron_variant,-2,0.514698,Pathogenic,True
9618,2101782473,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478939,SLC19A2,A,T,T:0.000156:1:1000Genomes_30X|T:0.000007:1:Gnom...,intron_variant,-2,0.505789,Pathogenic,True
9853,2526228997,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465907,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.808639,Pathogenic,False
9869,2526229323,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169466011,SLC19A2,A,G,G:0.0000021:3:GnomAD_exomes,intron_variant,-2,0.332860,Pathogenic,True
9966,2526234346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468152,SLC19A2,CAATTAGAGTGAGCA,CA,-:0.0000043:6:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.975035,Pathogenic,False
10053,2526235999,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468658,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.996009,Pathogenic,False
10061,2526236130,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468700,SLC19A2,G,-,-:0.00001:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.999329,Pathogenic,False
10064,2526236154,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468706,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.999566,Pathogenic,False
10072,2526236236,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468728,SLC19A2,-,C,C:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.918320,Pathogenic,False
10074,2526236253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468730,SLC19A2,-,TGCAGCA,TGCAGCA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.997474,Pathogenic,False
10075,2526236267,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468732,SLC19A2,-,CAGGAGAG,CAGGAGAG:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant;stop_gained,-2,0.999753,Pathogenic,False
10079,2526236348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468759,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999099,Pathogenic,False
10083,2526236371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468770,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999796,Pathogenic,False
10084,2526236447,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468791,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.999677,Pathogenic,False
10085,2526236453,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468791,SLC19A2,GACCAG,G,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.991713,Pathogenic,False
10087,2526236505,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468797,SLC19A2,-,TT,TT:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.951172,Pathogenic,False
10223,2526240071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470079,SLC19A2,AG,-,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999380,Pathogenic,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.997338,Pathogenic,False
10401,2526255842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477167,SLC19A2,G,-,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.946501,Pathogenic,False
10424,2526256167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477297,SLC19A2,-,T,T:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.947796,Pathogenic,False
10428,2526256643,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477335,SLC19A2,AGGTAAAAACCAGG,AGG,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999906,Pathogenic,False
10439,2526256896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477403,SLC19A2,GCGACCAGCCTGCCACTG,G,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999277,Pathogenic,False
10440,2526256902,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477403,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999260,Pathogenic,False
10441,2526256925,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477406,SLC19A2,-,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.998965,Pathogenic,False
10442,2526256938,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477408,SLC19A2,C,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;stop_ga...,-2,0.999426,Pathogenic,False
10448,2526257051,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477445,SLC19A2,A,T,T:0.000002:2:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-2,0.772864,Pathogenic,False
10458,2526257190,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477503,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999213,Pathogenic,False
10459,2526257209,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169477505,SLC19A2,TGCC,-,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999998,Pathogenic,False
10486,2526257854,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477696,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999920,Pathogenic,False
10721,2526274073,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485599,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.938775,Pathogenic,False
10746,2526275035,MDVPGPVSRRAAAAAPLCSCGPLGSVANAGSCRPRCSAPTASSPAS...,delins,169485721,SLC19A2,C,-,-:0.0000008:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999996,Pathogenic,False
10755,2526275248,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,snv,169485766,SLC19A2,T,C,C:0.000001:1:GnomAD_exomes,missense_variant;initiator_codon_variant,-2,0.927169,Pathogenic,False
10771,2526275649,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485808,SLC19A2,CTCCTCCTCC,CTCCTCC,-:0.0000023:3:GnomAD_exomes,5_prime_UTR_variant,-2,0.973480,Pathogenic,False
10791,2526276587,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485878,SLC19A2,CAGGACGTTC,C,-:0.0000009:1:GnomAD_exomes,5_prime_UTR_variant,-2,0.997641,Pathogenic,False
10802,2526276701,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485902,SLC19A2,CCTCC,C,-:0.000003:3:GnomAD_exomes,5_prime_UTR_variant,-2,0.924430,Pathogenic,False
10862,2526278693,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486483,SLC19A2,G,A,A:0.00001:1:TOMMO,2KB_upstream_variant;upstream_transcript_variant,-2,0.420958,Pathogenic,True
10889,34688678,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169473410,SLC19A2,TTTT,TTTTTTTTTTTT,-:0.4325:2166:1000Genomes|-:0.475:19:GENOME_DK...,intron_variant,-2,0.617425,Pathogenic,True
10942,35735941,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477744,SLC19A2,-,T,NaN,frameshift_variant;intron_variant;coding_seque...,-2,0.964579,Pathogenic,False
10998,375833910,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477105,SLC19A2,G,A,A:0.000008:1:ExAC|A:0.000007:1:GnomAD_genomes|...,intron_variant,-2,0.969687,Pathogenic,True
11572,750554176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477356,SLC19A2,A,-,-:0.000008:1:ExAC,coding_sequence_variant;intron_variant;framesh...,-2,0.999072,Pathogenic,False
11611,754086436,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465954,SLC19A2,A,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.993005,Pathogenic,False
11719,762044278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477211,SLC19A2,C,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant;int...,-2,0.682325,Pathogenic,False
11800,767845548,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477405,SLC19A2,G,T,A:0.000066:8:ExAC|A:0.0000435:61:GnomAD_exomes...,stop_gained;intron_variant;coding_sequence_var...,-2,0.999106,Pathogenic,False

In [ ]:
model.drop(columns=['protein_sequence'], inplace=True)

/tmp/ipykernel_44055/2808208366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pathogenic_new_model.drop(columns=['protein_sequence'], inplace=True)
/tmp/ipykernel_44055/2808208366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pathogenic_old_model.drop(columns=['protein_sequence'], inplace=True)

In [3]:
likely_pathogenic_model = model[model['Predicted_Label_Display'] == 'Likely Pathogenic']

In [4]:
likely_pathogenic_model.iloc[:50]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
2447,1002305755,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477958,SLC19A2,G,C,NaN,intron_variant,-1,0.652366,Likely Pathogenic,True
2490,1007033606,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480812,SLC19A2,T,A,NaN,intron_variant,-1,0.794178,Likely Pathogenic,True
2567,1016320124,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478301,SLC19A2,G,A,A:0.00002:3:GnomAD_genomes|A:0.00003:8:TOPMED|...,intron_variant,-1,0.530718,Likely Pathogenic,True
2591,1018486572,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480545,SLC19A2,C,T,NaN,intron_variant,-1,0.938531,Likely Pathogenic,True
2593,1018549401,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480822,SLC19A2,C,T,T:0.000101:15:GnomAD_genomes|T:0.000013:1:TOMM...,intron_variant,-1,0.665310,Likely Pathogenic,True
2615,1021035057,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470526,SLC19A2,G,T,T:0.000027:4:GnomAD_genomes|T:0.:0:ALFA,intron_variant,-1,0.473915,Likely Pathogenic,True
2636,1022724657,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479864,SLC19A2,G,A,C:0.000013:2:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.553024,Likely Pathogenic,True
2651,1024192776,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479556,SLC19A2,G,A,A:0.000013:2:GnomAD_genomes|A:0.000026:7:TOPME...,intron_variant,-1,0.682475,Likely Pathogenic,True
2680,1028030681,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470851,SLC19A2,C,G,G:0.000007:1:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-1,0.730303,Likely Pathogenic,True
2700,1029941510,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480275,SLC19A2,T,C,NaN,intron_variant,-1,0.700238,Likely Pathogenic,True
2730,1032519430,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477589,SLC19A2,G,T,T:0.000003:2:GnomAD_exomes,intron_variant;coding_sequence_variant;missens...,-1,0.476547,Likely Pathogenic,False
2751,1035361467,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481718,SLC19A2,A,G,NaN,intron_variant,-1,0.715930,Likely Pathogenic,True
2760,1036568273,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477925,SLC19A2,T,A,A:0.000013:2:GnomAD_genomes|A:0.000015:4:TOPME...,intron_variant,-1,0.527652,Likely Pathogenic,True
2823,1042685073,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482356,SLC19A2,A,G,G:0.000312:2:1000Genomes_30X|G:0.000261:39:Gno...,intron_variant,-1,0.507008,Likely Pathogenic,True
2824,1042737233,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482687,SLC19A2,A,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.512582,Likely Pathogenic,True
2880,1049847878,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479827,SLC19A2,T,G,NaN,intron_variant,-1,0.509187,Likely Pathogenic,True
2897,1051745914,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479610,SLC19A2,G,T,T:0.:0:ALFA,intron_variant,-1,0.487314,Likely Pathogenic,True
2927,1054210391,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477824,SLC19A2,G,T,T:0.0000016:2:GnomAD_exomes|T:0.0000135:2:Gnom...,intron_variant,-1,0.477450,Likely Pathogenic,True
2944,1055726292,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478268,SLC19A2,G,C,C:0.000008:2:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.615078,Likely Pathogenic,True
2971,111324338,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480395,SLC19A2,C,T,NaN,intron_variant,-1,0.582947,Likely Pathogenic,True
2977,112140613,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477835,SLC19A2,T,C,C:0.0000033:4:GnomAD_exomes,intron_variant,-1,0.596602,Likely Pathogenic,True
3004,114400094,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481597,SLC19A2,G,C,A:0.001:5:1000Genomes|A:0.00094:6:1000Genomes_...,intron_variant,-1,0.451761,Likely Pathogenic,True
3017,1157995859,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482344,SLC19A2,A,G,G:0.000007:1:GnomAD_genomes|G:0.:0:ALFA,intron_variant,-1,0.583027,Likely Pathogenic,True
3128,1169422753,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477628,SLC19A2,A,G,G:0.000002:1:GnomAD_exomes|G:0.:0:KOREAN|C:0.0...,intron_variant;coding_sequence_variant;missens...,-1,0.694156,Likely Pathogenic,False
3158,1172446053,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482502,SLC19A2,C,T,T:0.00411:12:KOREAN|T:0.00167:1:NorthernSweden...,intron_variant,-1,0.451970,Likely Pathogenic,True
3200,1178509794,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479342,SLC19A2,T,G,G:0.000007:1:GnomAD_genomes,intron_variant,-1,0.479821,Likely Pathogenic,True
3201,1178726679,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468215,SLC19A2,C,A,A:0.000002:1:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.724258,Likely Pathogenic,False
3206,1179287401,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480277,SLC19A2,C,T,T:0.00001:1:TOMMO,intron_variant,-1,0.551778,Likely Pathogenic,True
3218,1181152160,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482484,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|A:0.000004:1:TOPME...,intron_variant,-1,0.485519,Likely Pathogenic,True
3219,1181152160,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482484,SLC19A2,T,A,C:0.000007:1:GnomAD_genomes|A:0.000004:1:TOPME...,intron_variant,-1,0.518566,Likely Pathogenic,True
3270,1185127462,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481044,SLC19A2,T,A,A:0.000011:3:TOPMED|A:0.:0:ALFA,intron_variant,-1,0.495771,Likely Pathogenic,True
3284,1187792761,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481651,SLC19A2,A,G,G:0.000007:1:GnomAD_genomes|G:0.000013:1:TOMMO...,intron_variant,-1,0.658582,Likely Pathogenic,True
3319,1193545814,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477701,SLC19A2,A,C,C:0.000003:2:GnomAD_exomes|C:0.000023:6:TOPMED...,synonymous_variant;coding_sequence_variant;int...,-1,0.538016,Likely Pathogenic,True
3339,1195399818,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477931,SLC19A2,G,T,T:0.0002:1:Estonian|T:0.0002:1:ALFA,intron_variant,-1,0.517446,Likely Pathogenic,True
3344,1195909186,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480311,SLC19A2,T,C,C:0.000019:5:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.652235,Likely Pathogenic,True
3345,1195909186,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480311,SLC19A2,T,A,C:0.000019:5:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.735763,Likely Pathogenic,True
3357,1196607438,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481611,SLC19A2,A,T,T:0.00002:3:GnomAD_genomes|T:0.000019:5:TOPMED...,intron_variant,-1,0.473198,Likely Pathogenic,True
3380,1198926832,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470861,SLC19A2,T,C,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,intron_variant,-1,0.620213,Likely Pathogenic,True
3463,1207369517,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478827,SLC19A2,T,C,C:0.:0:ALFA,intron_variant,-1,0.638025,Likely Pathogenic,True
3475,1208427662,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482348,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-1,0.506518,Likely Pathogenic,True
3531,12139393,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479692,SLC19A2,G,A,A:0.:0:HapMap,intron_variant,-1,0.563941,Likely Pathogenic,True
3557,1216358814,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470086,SLC19A2,G,A,A:0.0000043:6:GnomAD_exomes|A:0.000037:1:ALFA,missense_variant;coding_sequence_variant,-1,0.543309,Likely Pathogenic,False
3558,1216358814,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470086,SLC19A2,G,C,A:0.0000043:6:GnomAD_exomes|A:0.000037:1:ALFA,missense_variant;coding_sequence_variant,-1,0.552793,Likely Pathogenic,False
3578,1219241010,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481317,SLC19A2,G,A,A:0.000013:2:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.515517,Likely Pathogenic,True
3579,1219241010,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481317,SLC19A2,G,C,A:0.000013:2:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.501763,Likely Pathogenic,True
3674,1230542836,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480257,SLC19A2,C,A,A:0.000004:1:TOPMED|A:0.000071:1:ALFA,intron_variant,-1,0.542855,Likely Pathogenic,True
3729,1235635904,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482447,SLC19A2,A,G,G:0.000013:2:GnomAD_genomes|G:0.000008:2:TOPME...,intron_variant,-1,0.513493,Likely Pathogenic,True
3749,1238024588,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482485,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.000071:1:ALFA,intron_variant,-1,0.529187,Likely Pathogenic,True
3781,1241795823,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481211,SLC19A2,C,T,T:0.000007:1:GnomAD_genomes|T:0.000004:1:TOPME...,intron_variant,-1,0.490167,Likely Pathogenic,True
3831,1246947125,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477761,SLC19A2,G,C,C:0.000004:1:TOPMED|A:0.000102:2:ALFA,intron_variant,-1,0.512942,Likely Pathogenic,True

In [5]:
def calculate_label_statistics(df, label="Pathogenic"):
    
    filtered_df = df[df['Predicted_Label_Display'] == label]
    number_of_variants = filtered_df.shape[0]
    number_of_mutated_protien_seq = filtered_df[filtered_df['normal_seq'] == False].shape[0]
    number_of_normal_protien_seq = filtered_df[filtered_df['normal_seq'] == True].shape[0]
    mutated_percentage_to_total = (number_of_mutated_protien_seq / number_of_variants * 100) if number_of_variants > 0 else 0
    average_confidence = filtered_df['Prediction_Confidence'].mean()
    average_confidence_normal = filtered_df[filtered_df['normal_seq'] == True]['Prediction_Confidence'].mean()
    average_confidence_mutated = filtered_df[filtered_df['normal_seq'] == False]['Prediction_Confidence'].mean()

    return {
        "number_of_variants": number_of_variants,
        "number_of_mutated_protien_seq": number_of_mutated_protien_seq,
        "number_of_normal_protien_seq": number_of_normal_protien_seq,
        "mutated_percentage_to_total": mutated_percentage_to_total,
        "average_confidence": average_confidence,
        "average_confidence_normal": average_confidence_normal,
        "average_confidence_mutated": average_confidence_mutated
    }


pathogenic_old_model_stats = calculate_label_statistics(model, "Pathogenic")
likely_pathogenic_old_model_stats = calculate_label_statistics(model, "Likely Pathogenic")
benign_old_model_stats = calculate_label_statistics(model, "Benign")
likely_benign_old_model_stats = calculate_label_statistics(model, "Likely Benign")

print("pathogenic old model stats")
for stat in pathogenic_old_model_stats:
    print(f"Old Model - {stat}: {pathogenic_old_model_stats[stat]}")
print("=" * 50)
print("likely pathogenic old model stats")
for stat in likely_pathogenic_old_model_stats:
    print(f"Likely Pathogenic Old Model - {stat}: {likely_pathogenic_old_model_stats[stat]}")
print("=" * 50)

print("benign old model stats")
for stat in benign_old_model_stats:
    print(f"Benign Old Model - {stat}: {benign_old_model_stats[stat]}")
print("=" * 50)
print("likely benign old model stats")
for stat in likely_benign_old_model_stats:
    print(f"Likely Benign Old Model - {stat}: {likely_benign_old_model_stats[stat]}")

pathogenic old model stats
Old Model - number_of_variants: 269
Old Model - number_of_mutated_protien_seq: 112
Old Model - number_of_normal_protien_seq: 157
Old Model - mutated_percentage_to_total: 41.63568773234201
Old Model - average_confidence: 0.6942848383271375
Old Model - average_confidence_normal: 0.5693499562420382
Old Model - average_confidence_mutated: 0.86941677125
==================================================
likely pathogenic old model stats
Likely Pathogenic Old Model - number_of_variants: 1542
Likely Pathogenic Old Model - number_of_mutated_protien_seq: 290
Likely Pathogenic Old Model - number_of_normal_protien_seq: 1252
Likely Pathogenic Old Model - mutated_percentage_to_total: 18.80674448767834
Likely Pathogenic Old Model - average_confidence: 0.6074141002853437
Likely Pathogenic Old Model - average_confidence_normal: 0.5994351948083066
Likely Pathogenic Old Model - average_confidence_mutated: 0.6418609611724138
==================================================
benign old model stats
Benign Old Model - number_of_variants: 3565
Benign Old Model - number_of_mutated_protien_seq: 13
Benign Old Model - number_of_normal_protien_seq: 3552
Benign Old Model - mutated_percentage_to_total: 0.364656381486676
Benign Old Model - average_confidence: 0.7165464745666199
Benign Old Model - average_confidence_normal: 0.717135030382883
Benign Old Model - average_confidence_mutated: 0.5557349161538462
==================================================
likely benign old model stats
Likely Benign Old Model - number_of_variants: 23241
Likely Benign Old Model - number_of_mutated_protien_seq: 810
Likely Benign Old Model - number_of_normal_protien_seq: 22431
Likely Benign Old Model - mutated_percentage_to_total: 3.485220085194269
Likely Benign Old Model - average_confidence: 0.6922310741517147
Likely Benign Old Model - average_confidence_normal: 0.6918921500628594
Likely Benign Old Model - average_confidence_mutated: 0.7016167608641974

In [ ]:
"""

def calculate_label_statistics(df, label="Pathogenic"):
    
    filtered_df = df[df['Predicted_Label_Display'] == label]
    number_of_variants = filtered_df.shape[0]
    number_of_mutated_protien_seq = filtered_df[filtered_df['normal_seq'] == False].shape[0]
    number_of_normal_protien_seq = filtered_df[filtered_df['normal_seq'] == True].shape[0]
    mutated_percentage_to_total = (number_of_mutated_protien_seq / number_of_variants * 100) if number_of_variants > 0 else 0
    average_confidence = filtered_df['Prediction_Confidence'].mean()
    average_confidence_normal = filtered_df[filtered_df['normal_seq'] == True]['Prediction_Confidence'].mean()
    average_confidence_mutated = filtered_df[filtered_df['normal_seq'] == False]['Prediction_Confidence'].mean()

    return {
        "number_of_variants": number_of_variants,
        "number_of_mutated_protien_seq": number_of_mutated_protien_seq,
        "number_of_normal_protien_seq": number_of_normal_protien_seq,
        "mutated_percentage_to_total": mutated_percentage_to_total,
        "average_confidence": average_confidence,
        "average_confidence_normal": average_confidence_normal,
        "average_confidence_mutated": average_confidence_mutated
    }


pathogenic_old_model_stats = calculate_label_statistics(old_model, "Pathogenic")
pathogenic_new_model_stats = calculate_label_statistics(new_model, "Pathogenic")
pathogenic_newest_model_stats = calculate_label_statistics(newest_model, "Pathogenic")
pathogenic_model_4_stats = calculate_label_statistics(model_4, "Pathogenic")
pathogenic_model_5_stats = calculate_label_statistics(model_5, "Pathogenic")
pathogenic_model_6_stats = calculate_label_statistics(model_6, "Pathogenic")

likely_pathogenic_old_model_stats = calculate_label_statistics(old_model, "Likely Pathogenic")
likely_pathogenic_new_model_stats = calculate_label_statistics(new_model, "Likely Pathogenic")
likely_pathogenic_newest_model_stats = calculate_label_statistics(newest_model, "Likely Pathogenic")
likely_pathogenic_model_4_stats = calculate_label_statistics(model_4, "Likely Pathogenic")
likely_pathogenic_model_5_stats = calculate_label_statistics(model_5, "Likely Pathogenic")
likely_pathogenic_model_6_stats = calculate_label_statistics(model_6, "Likely Pathogenic")

benign_old_model_stats = calculate_label_statistics(old_model, "Benign")
benign_new_model_stats = calculate_label_statistics(new_model, "Benign")
benign_newest_model_stats = calculate_label_statistics(newest_model, "Benign")
benign_model_4_stats = calculate_label_statistics(model_4, "Benign")
benign_model_5_stats = calculate_label_statistics(model_5, "Benign")
benign_model_6_stats = calculate_label_statistics(model_6, "Benign")

likely_benign_old_model_stats = calculate_label_statistics(old_model, "Likely Benign")
likely_benign_new_model_stats = calculate_label_statistics(new_model, "Likely Benign")
likely_benign_newest_model_stats = calculate_label_statistics(newest_model, "Likely Benign")
likely_benign_model_4_stats = calculate_label_statistics(model_4, "Likely Benign")
likely_benign_model_5_stats = calculate_label_statistics(model_5, "Likely Benign")
likely_benign_model_6_stats = calculate_label_statistics(model_6, "Likely Benign")

print("pathogenic old model stats")
for stat in pathogenic_old_model_stats:
    print(f"Old Model - {stat}: {pathogenic_old_model_stats[stat]}")
print("=" * 50)

print("pathogenic new model stats")
for stat in pathogenic_new_model_stats:
    print(f"New Model - {stat}: {pathogenic_new_model_stats[stat]}")
print("=" * 50)

print("pathogenic newest model stats")
for stat in pathogenic_newest_model_stats:
    print(f"Newest Model - {stat}: {pathogenic_newest_model_stats[stat]}")
print("=" * 50)

print("Pathogenic Model 4 Stats")
for stat in pathogenic_model_4_stats:
    print(f"Model 4 - {stat}: {pathogenic_model_4_stats[stat]}")
print("=" * 50)

print("Pathogenic Model 5 Stats")
for stat in pathogenic_model_5_stats:
    print(f"Model 5 - {stat}: {pathogenic_model_5_stats[stat]}")
print("=" * 50)

print("pathogenic model 6 stats")
for stat in pathogenic_model_6_stats:
    print(f"Model 6 - {stat}: {pathogenic_model_6_stats[stat]}")
print("=" * 50)

# ===================================================

print("likely pathogenic old model stats")
for stat in likely_pathogenic_old_model_stats:
    print(f"Likely Pathogenic Old Model - {stat}: {likely_pathogenic_old_model_stats[stat]}")
print("=" * 50)

print("likely pathogenic new model stats")
for stat in likely_pathogenic_new_model_stats:
    print(f"Likely Pathogenic New Model - {stat}: {likely_pathogenic_new_model_stats[stat]}")

print("=" * 50)


print("likely pathogenic newest model stats")
for stat in likely_pathogenic_newest_model_stats:
    print(f"Likely Pathogenic Newest Model - {stat}: {likely_pathogenic_newest_model_stats[stat]}")

print("=" * 50)

print("Likely Pathogenic Model 4 Stats")
for stat in likely_pathogenic_model_4_stats:
    print(f"Model 4 - {stat}: {likely_pathogenic_model_4_stats[stat]}")
print("=" * 50)

print("Likely Pathogenic Model 5 Stats")
for stat in likely_pathogenic_model_5_stats:
    print(f"Model 5 - {stat}: {likely_pathogenic_model_5_stats[stat]}")
print("=" * 50)

print("Likely Pathogenic Model 6 Stats")
for stat in likely_pathogenic_model_6_stats:
    print(f"Model 6 - {stat}: {likely_pathogenic_model_6_stats[stat]}")
print("=" * 50)

# ===================================================

print("benign old model stats")
for stat in benign_old_model_stats:
    print(f"Benign Old Model - {stat}: {benign_old_model_stats[stat]}")
print("=" * 50)

print("benign new model stats")
for stat in benign_new_model_stats:
    print(f"Benign New Model - {stat}: {benign_new_model_stats[stat]}")
print("=" * 50)

print("benign newest model stats")
for stat in benign_newest_model_stats:
    print(f"Benign Newest Model - {stat}: {benign_newest_model_stats[stat]}")
print("=" * 50)

print("benign model 4 stats")
for stat in benign_model_4_stats:
    print(f"Model 4 - {stat}: {benign_model_4_stats[stat]}")
print("=" * 50)

print("benign model 5 stats")
for stat in benign_model_5_stats:
    print(f"Model 5 - {stat}: {benign_model_5_stats[stat]}")
print("=" * 50)

print("benign model 6 stats")
for stat in benign_model_6_stats:
    print(f"Model 6 - {stat}: {benign_model_6_stats[stat]}")
print("=" * 50)

# =================================


print("likely benign old model stats")
for stat in likely_benign_old_model_stats:
    print(f"Likely Benign Old Model - {stat}: {likely_benign_old_model_stats[stat]}")
print("=" * 50)

print("likely benign new model stats")
for stat in likely_benign_new_model_stats:
    print(f"Likely Benign New Model - {stat}: {likely_benign_new_model_stats[stat]}")
print("=" * 50)

print("likely benign newest model stats")
for stat in likely_benign_newest_model_stats:
    print(f"Likely Benign Newest Model - {stat}: {likely_benign_newest_model_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 4 Stats")
for stat in likely_benign_model_4_stats:
    print(f"Model 4 - {stat}: {likely_benign_model_4_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 5 Stats")
for stat in likely_benign_model_5_stats:
    print(f"Model 5 - {stat}: {likely_benign_model_5_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 6 Stats")
for stat in likely_benign_model_6_stats:
    print(f"Model 6 - {stat}: {likely_benign_model_6_stats[stat]}")
print("=" * 50)
"""

pathogenic old model stats
Old Model - number_of_variants: 251
Old Model - number_of_mutated_protien_seq: 125
Old Model - number_of_normal_protien_seq: 126
Old Model - mutated_percentage_to_total: 49.800796812749006
Old Model - average_confidence: 0.7514298591633466
Old Model - average_confidence_normal: 0.6228570367460318
Old Model - average_confidence_mutated: 0.8810312641600001
==================================================
pathogenic new model stats
New Model - number_of_variants: 105
New Model - number_of_mutated_protien_seq: 93
New Model - number_of_normal_protien_seq: 12
New Model - mutated_percentage_to_total: 88.57142857142857
New Model - average_confidence: 0.8539132496190477
New Model - average_confidence_normal: 0.5075782499999999
New Model - average_confidence_mutated: 0.8986016366666668
==================================================
pathogenic newest model stats
Newest Model - number_of_variants: 234
Newest Model - number_of_mutated_protien_seq: 114
Newest Model - number_of_normal_protien_seq: 120
Newest Model - mutated_percentage_to_total: 48.717948717948715
Newest Model - average_confidence: 0.8531088866239317
Newest Model - average_confidence_normal: 0.7938893208333333
Newest Model - average_confidence_mutated: 0.9154452716666667
==================================================
Pathogenic Model 4 Stats
Model 4 - number_of_variants: 279
Model 4 - number_of_mutated_protien_seq: 132
Model 4 - number_of_normal_protien_seq: 147
Model 4 - mutated_percentage_to_total: 47.31182795698925
Model 4 - average_confidence: 0.6866204480645162
Model 4 - average_confidence_normal: 0.5626304819727891
Model 4 - average_confidence_mutated: 0.8247001830303031
==================================================
Pathogenic Model 5 Stats
Model 5 - number_of_variants: 202
Model 5 - number_of_mutated_protien_seq: 107
Model 5 - number_of_normal_protien_seq: 95
Model 5 - mutated_percentage_to_total: 52.97029702970298
Model 5 - average_confidence: 0.7355079802475247
Model 5 - average_confidence_normal: 0.5658767661052632
Model 5 - average_confidence_mutated: 0.8861151329906541
==================================================
pathogenic model 6 stats
Model 6 - number_of_variants: 141
Model 6 - number_of_mutated_protien_seq: 112
Model 6 - number_of_normal_protien_seq: 29
Model 6 - mutated_percentage_to_total: 79.43262411347519
Model 6 - average_confidence: 0.7222760261702129
Model 6 - average_confidence_normal: 0.44962504724137936
Model 6 - average_confidence_mutated: 0.7928731546428571
==================================================
likely pathogenic old model stats
Likely Pathogenic Old Model - number_of_variants: 2022
Likely Pathogenic Old Model - number_of_mutated_protien_seq: 364
Likely Pathogenic Old Model - number_of_normal_protien_seq: 1658
Likely Pathogenic Old Model - mutated_percentage_to_total: 18.001978239366963
Likely Pathogenic Old Model - average_confidence: 0.7308950470524234
Likely Pathogenic Old Model - average_confidence_normal: 0.7245090121652594
Likely Pathogenic Old Model - average_confidence_mutated: 0.7599830850824175
==================================================
likely pathogenic new model stats
Likely Pathogenic New Model - number_of_variants: 1959
Likely Pathogenic New Model - number_of_mutated_protien_seq: 250
Likely Pathogenic New Model - number_of_normal_protien_seq: 1709
Likely Pathogenic New Model - mutated_percentage_to_total: 12.76161306789178
Likely Pathogenic New Model - average_confidence: 0.5439167837161818
Likely Pathogenic New Model - average_confidence_normal: 0.5368088315272089
Likely Pathogenic New Model - average_confidence_mutated: 0.59250674488
==================================================
likely pathogenic newest model stats
Likely Pathogenic Newest Model - number_of_variants: 873
Likely Pathogenic Newest Model - number_of_mutated_protien_seq: 120
Likely Pathogenic Newest Model - number_of_normal_protien_seq: 753
Likely Pathogenic Newest Model - mutated_percentage_to_total: 13.745704467353953
Likely Pathogenic Newest Model - average_confidence: 0.7691624626689577
Likely Pathogenic Newest Model - average_confidence_normal: 0.7651098529349271
Likely Pathogenic Newest Model - average_confidence_mutated: 0.79459258875
==================================================
Likely Pathogenic Model 4 Stats
Model 4 - number_of_variants: 1522
Model 4 - number_of_mutated_protien_seq: 325
Model 4 - number_of_normal_protien_seq: 1197
Model 4 - mutated_percentage_to_total: 21.353482260183966
Model 4 - average_confidence: 0.7171144692509857
Model 4 - average_confidence_normal: 0.7044335796407686
Model 4 - average_confidence_mutated: 0.7638191611384615
==================================================
Likely Pathogenic Model 5 Stats
Model 5 - number_of_variants: 1351
Model 5 - number_of_mutated_protien_seq: 234
Model 5 - number_of_normal_protien_seq: 1117
Model 5 - mutated_percentage_to_total: 17.320503330866025
Model 5 - average_confidence: 0.6932578299777942
Model 5 - average_confidence_normal: 0.6835558406535363
Model 5 - average_confidence_mutated: 0.7395703174786326
==================================================
Likely Pathogenic Model 6 Stats
Model 6 - number_of_variants: 110
Model 6 - number_of_mutated_protien_seq: 30
Model 6 - number_of_normal_protien_seq: 80
Model 6 - mutated_percentage_to_total: 27.27272727272727
Model 6 - average_confidence: 0.38459133963636366
Model 6 - average_confidence_normal: 0.377933813375
Model 6 - average_confidence_mutated: 0.40234474299999995
==================================================
benign old model stats
Benign Old Model - number_of_variants: 4306
Benign Old Model - number_of_mutated_protien_seq: 15
Benign Old Model - number_of_normal_protien_seq: 4291
Benign Old Model - mutated_percentage_to_total: 0.34835113794705064
Benign Old Model - average_confidence: 0.7943513138086391
Benign Old Model - average_confidence_normal: 0.7950128199021207
Benign Old Model - average_confidence_mutated: 0.6051164706666666
==================================================
benign new model stats
Benign New Model - number_of_variants: 4427
Benign New Model - number_of_mutated_protien_seq: 33
Benign New Model - number_of_normal_protien_seq: 4394
Benign New Model - mutated_percentage_to_total: 0.7454257962502824
Benign New Model - average_confidence: 0.6291529043934945
Benign New Model - average_confidence_normal: 0.6301557763222576
Benign New Model - average_confidence_mutated: 0.49561898757575756
==================================================
benign newest model stats
Benign Newest Model - number_of_variants: 3097
Benign Newest Model - number_of_mutated_protien_seq: 7
Benign Newest Model - number_of_normal_protien_seq: 3090
Benign Newest Model - mutated_percentage_to_total: 0.22602518566354535
Benign Newest Model - average_confidence: 0.8043134271197934
Benign Newest Model - average_confidence_normal: 0.8046280603786408
Benign Newest Model - average_confidence_mutated: 0.665425317142857
==================================================
benign model 4 stats
Model 4 - number_of_variants: 3910
Model 4 - number_of_mutated_protien_seq: 18
Model 4 - number_of_normal_protien_seq: 3892
Model 4 - mutated_percentage_to_total: 0.46035805626598464
Model 4 - average_confidence: 0.8208912240204604
Model 4 - average_confidence_normal: 0.8216579678288798
Model 4 - average_confidence_mutated: 0.6551041738888889
==================================================
benign model 5 stats
Model 5 - number_of_variants: 3666
Model 5 - number_of_mutated_protien_seq: 14
Model 5 - number_of_normal_protien_seq: 3652
Model 5 - mutated_percentage_to_total: 0.3818876159301691
Model 5 - average_confidence: 0.7745140485242773
Model 5 - average_confidence_normal: 0.7751521063472071
Model 5 - average_confidence_mutated: 0.6080721078571428
==================================================
benign model 6 stats
Model 6 - number_of_variants: 1606
Model 6 - number_of_mutated_protien_seq: 3
Model 6 - number_of_normal_protien_seq: 1603
Model 6 - mutated_percentage_to_total: 0.18679950186799502
Model 6 - average_confidence: 0.8015402536861768
Model 6 - average_confidence_normal: 0.8021137544603867
Model 6 - average_confidence_mutated: 0.4950996733333333
==================================================
likely benign old model stats
Likely Benign Old Model - number_of_variants: 22185
Likely Benign Old Model - number_of_mutated_protien_seq: 729
Likely Benign Old Model - number_of_normal_protien_seq: 21456
Likely Benign Old Model - mutated_percentage_to_total: 3.286004056795132
Likely Benign Old Model - average_confidence: 0.7865933791877395
Likely Benign Old Model - average_confidence_normal: 0.7868266810887398
Likely Benign Old Model - average_confidence_mutated: 0.7797268145953362
==================================================
likely benign new model stats
Likely Benign New Model - number_of_variants: 22273
Likely Benign New Model - number_of_mutated_protien_seq: 849
Likely Benign New Model - number_of_normal_protien_seq: 21424
Likely Benign New Model - mutated_percentage_to_total: 3.8117900597135543
Likely Benign New Model - average_confidence: 0.5298210714326764
Likely Benign New Model - average_confidence_normal: 0.528394082098581
Likely Benign New Model - average_confidence_mutated: 0.5658302816725559
==================================================
likely benign newest model stats
Likely Benign Newest Model - number_of_variants: 24560
Likely Benign Newest Model - number_of_mutated_protien_seq: 984
Likely Benign Newest Model - number_of_normal_protien_seq: 23576
Likely Benign Newest Model - mutated_percentage_to_total: 4.006514657980456
Likely Benign Newest Model - average_confidence: 0.9027369850207655
Likely Benign Newest Model - average_confidence_normal: 0.9023020224567356
Likely Benign Newest Model - average_confidence_mutated: 0.913158405152439
==================================================
Likely Benign Model 4 Stats
Model 4 - number_of_variants: 14742
Model 4 - number_of_mutated_protien_seq: 608
Model 4 - number_of_normal_protien_seq: 14134
Model 4 - mutated_percentage_to_total: 4.124270790937458
Model 4 - average_confidence: 0.7820728913498847
Model 4 - average_confidence_normal: 0.7820671184448847
Model 4 - average_confidence_mutated: 0.7822070924013158
==================================================
Likely Benign Model 5 Stats
Model 5 - number_of_variants: 22581
Model 5 - number_of_mutated_protien_seq: 838
Model 5 - number_of_normal_protien_seq: 21743
Model 5 - mutated_percentage_to_total: 3.711084540100084
Model 5 - average_confidence: 0.7659100036982418
Model 5 - average_confidence_normal: 0.7652936844464885
Model 5 - average_confidence_mutated: 0.7819012083412887
==================================================
Likely Benign Model 6 Stats
Model 6 - number_of_variants: 26677
Model 6 - number_of_mutated_protien_seq: 1079
Model 6 - number_of_normal_protien_seq: 25598
Model 6 - mutated_percentage_to_total: 4.044682685459384
Model 6 - average_confidence: 0.9271642198605541
Model 6 - average_confidence_normal: 0.9297138085295725
Model 6 - average_confidence_mutated: 0.8666782414087117
==================================================

In [6]:
model_6_not_normal = model[model['normal_seq'] == False]
model_6_not_normal = model_6_not_normal[model_6_not_normal['gene'] == "SLC19A2"]

print("Available rows per label:")
for lbl in ["Pathogenic", "Likely Pathogenic", "Benign", "Likely Benign"]:
    count = (model_6_not_normal['Predicted_Label_Display'] == lbl).sum()
    print(f"{lbl}: {count} rows")

Available rows per label:
Pathogenic: 64 rows
Likely Pathogenic: 95 rows
Benign: 0 rows
Likely Benign: 532 rows

In [7]:


seed = 65

desired_counts = {
    "Pathogenic": 3,
    "Likely Pathogenic": 2,
    "Benign": 3,
    "Likely Benign": 2
}
parts = []

for lbl, cnt in desired_counts.items():
    pool = model_6_not_normal[model_6_not_normal['Predicted_Label_Display'] == lbl]
    picked = pool.sample(n=cnt, random_state=seed)  # same seed for every label
    parts.append(picked)

# Deterministic overall ordering (optional shuffle; still reproducible with seed)
selected = pd.concat(parts)
selected = selected.sample(frac=1, random_state=seed).copy()  # remove this line if you prefer grouped by label

# Inspect
print(selected['Predicted_Label_Display'].value_counts())
print(model_6.loc[selected.index, 'normal_seq'].value_counts())

ValueError: a must be greater than 0 unless no samples are taken

In [24]:
selected

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
10476,2526257694,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477666,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.389137,Likely Pathogenic,False
8067,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.741842,Pathogenic,False
11541,747950227,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470065,SLC19A2,A,G,G:0.000008:1:ExAC|G:0.000003:2:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.342136,Likely Pathogenic,False
4278,1296969176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468716,SLC19A2,C,A,T:0.0000029:4:GnomAD_exomes|T:0.0000067:1:Gnom...,coding_sequence_variant;missense_variant,2,0.670316,Benign,False
11849,772048171,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468699,SLC19A2,A,-,-:0.0000247:3:ExAC|-:0.:0:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.921596,Pathogenic,False
5282,1409662486,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485603,SLC19A2,G,T,C:0.000004:1:TOPMED|C:0.:0:ALFA,coding_sequence_variant;missense_variant,2,0.500523,Benign,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.964400,Pathogenic,False
12722,957742567,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470117,SLC19A2,G,A,A:0.00001:6:GnomAD_exomes|A:0.000007:1:GnomAD_...,coding_sequence_variant;missense_variant,1,0.938630,Likely Benign,False
3746,1237709955,MDVPGPVSRLAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485738,SLC19A2,C,A,A:0.0000023:3:GnomAD_exomes,coding_sequence_variant;missense_variant,1,0.974586,Likely Benign,False
3185,1176088261,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485609,SLC19A2,A,G,G:0.000223:1:Estonian|G:0.000007:1:GnomAD_geno...,coding_sequence_variant;missense_variant,2,0.314461,Benign,False

In [14]:
selected = pd.read_csv("results/selected_variants.csv")

In [16]:
selected

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq,dna_sequence,dna_sequence.1,dna_sequence.2
0,1176088261,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485609,SLC19A2,A,G,G:0.000223:1:Estonian|G:0.000007:1:GnomAD_geno...,coding_sequence_variant;missense_variant,2,0.314461,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
1,2526236089,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468692,SLC19A2,G,A,NaN,missense_variant;coding_sequence_variant,1,0.940814,Likely Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
2,1409662486,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485603,SLC19A2,G,T,C:0.000004:1:TOPMED|C:0.:0:ALFA,coding_sequence_variant;missense_variant,2,0.500523,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
3,2526256938,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477408,SLC19A2,C,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;stop_ga...,-2,0.911753,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
4,1034063734,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227695914,SLC19A3,A,G,NaN,coding_sequence_variant;missense_variant,-1,0.414397,Likely Pathogenic,False,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...
5,1658538909,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485565,SLC19A2,C,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-2,0.907458,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
6,1296969176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468716,SLC19A2,C,A,T:0.0000029:4:GnomAD_exomes|T:0.0000067:1:Gnom...,coding_sequence_variant;missense_variant,2,0.670316,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
7,1695589066,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699491,SLC19A3,T,C,C:0.00005:1:ALFA,coding_sequence_variant;missense_variant,-1,0.419081,Likely Pathogenic,False,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...,CTATGCATGAATGAATGAATTCCTCAATATCTCTCTCTGATTTAGA...
8,112877627,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468713,SLC19A2,T,C,C:0.0000014:2:GnomAD_exomes,coding_sequence_variant;missense_variant,1,0.994413,Likely Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
9,2526275248,MDLLLPGATVSCVPCHRLPPL,snv,169485766,SLC19A2,T,C,C:0.000001:1:GnomAD_exomes,missense_variant;initiator_codon_variant,-2,0.956032,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...,NaN,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...

In [ ]:
normal_mrna_slc19a2 = 'AGAGGCGUCUGUAGGGUAAAGCUGGGGGUUCUGUAGCCGGAGGCGGCGGCGAGUCCAGAACGUCCUGGCCUUACAGGGAGAAGGCGUCACUCGCGGUUACAAGUGCCUGACCCUCACUCCAGUUGGCGGAGGAGGAGAAGGAAGGGGCCGGGCCGGGUCCCCUCCCCUCGCGCCCCGGAUGGAUGUGCCCGGCCCGGUGUCUCGGCGGGCGGCGGCGGCGGCGGCCACUGUGCUCCUGCGGACCGCUCGGGUCCGUCGCGAAUGCUGGUUCUUGCCGACCGCGCUGCUCUGCGCCUACGGCUUCUUCGCCAGCCUCAGGCCGUCCGAGCCCUUCCUGACCCCGUACCUGCUGGGGCCGGACAAGAACCUGACCGAGAGGGAGGUCUUCAAUGAAAUUUAUCCAGUAUGGACUUACUCUUACCUGGUGCUACUGUUUCCUGUGUUCCUUGCCACAGACUACCUCCGUUAUAAACCUGUUGUUCUACUGCAGGGGCUCAGCCUUAUUGUUACAUGGUUUAUGCUGCUCUAUGCCCAGGGACUGCUGGCCAUUCAAUUUCUAGAAUUUUUUUAUGGCAUCGCCACAGCCACUGAAAUUGCCUAUUACUCUUAUAUCUACAGUGUGGUGGACCUGGGCAUGUACCAGAAAGUCACAAGUUACUGUCGAAGUGCCACUUUGGUGGGCUUUACAGUGGGCUCUGUCCUAGGGCAAAUCCUUGUCUCAGUGGCAGGCUGGUCGCUGUUCAGCCUGAAUGUCAUCUCUCUUACCUGUGUUUCAGUGGCUUUUGCUGUGGCCUGGUUUUUACCUAUGCCACAGAAGAGCCUCUUCUUUCACCACAUUCCUUCUACCUGCCAGAGAGUGAAUGGCAUCAAGGUACAAAAUGGUGGCAUUGUUACUGACACCCCAGCUUCUAACCACCUUCCUGGCUGGGAGGACAUUGAGUCAAAAAUCCCUCUAAAUAUGGAGGAGCCUCCCGUGGAGGAACCGGAACCCAAGCCAGACCGUCUCCUUGUAUUGAAAGUACUAUGGAAUGAUUUCCUGAUGUGCUACUCCUCUCGCCCUCUUCUCUGCUGGUCUGUGUGGUGGGCCCUCUCUACCUGUGGCUAUUUUCAAGUUGUGAACUACACACAGGGCCUGUGGGAGAAAGUGAUGCCUUCUCGCUAUGCUGCUAUCUAUAAUGGUGGCGUGGAGGCCGUUUCAACCUUACUGGGUGCUGUUGCUGUGUUUGCAGUUGGUUAUAUAAAAAUAUCCUGGUCAACUUGGGGAGAAAUGACAUUAUCUCUCUUUUCUCUCCUGAUUGCUGCUGCAGUGUAUAUCAUGGACACUGUGGGUAACAUUUGGGUGUGCUAUGCAUCCUAUGUUGUCUUCAGAAUCAUCUACAUGUUACUCAUCACGAUAGCAACUUUUCAAAUUGCUGCAAACCUCAGCAUGGAACGCUAUGCCCUAGUAUUUGGUGUAAAUACCUUCAUUGCCCUGGCACUGCAGACGCUGCUCACUCUAAUUGUGGUAGAUGCCAGUGGCCUUGGAUUAGAAAUUACCACUCAGUUUUUGAUCUAUGCCAGUUAUUUUGCACUCAUCGCUGUGGUUUUCCUGGCCAGUGGUGCAGUCAGUGUUAUGAAGAAAUGUAGAAAGCUGGAAGAUCCACAAUCAAGUUCUCAAGUAACCACUUCAUAAUAUACUGCUGAAGGGCUUCUUCUUAUAGCAAGAACUCUGCACAGCAACUGCCUGGAUGUGUUUGAUUUUUUAAAGCGUAGACAUAUAUUUAUGAAUGUGCAUUUCUUGACUUCACAGCAGCCACUUGACUAAUACCUUGUGUUCCGGGAAUAACAUGAUACUAUUCAGAGGAGCCAGAAGUAAAGUUUAUUUCAUGGAUUAUUUAUGAGAGCUAAUUUAAGGAUGACUUUUUUUCUGAUUCAAAAGUGAACUUGAUUUUAAAAACCAGUCAAGAGCAAUCAAAGCAGCACAUGGUGUUGUAUACUUCAUUAGCAAGUGAGUUUGGUGUUUUAUAGGUCACAUAUGUCUGUAUCUACUUAGCCAGAUGCUUGGCCUGGUGGGACCAGGGCUCCACAGAGGCCACAAAAUGUUGCAAGUCAUGAUGGAUGGAAAUAUGUUCUAACAGCAUCUGCCUCUAUUCAAUUUAAUUCUUAUUUCUGUGUUACUCAUGUACAUUGGUCUUUCUACAUAGUUAUUCUAUCACUGGCAAUAUUUGUUCUGGUUUAGUGUUCUGUAUUUUAAGGUGUACGUAUCAUUUCUAAUUUUAAGUUAUUUUAAAAAAAUUCAUCAUAUGAAUGUUCUUGGUUCCCAUUGUGACGAUUAUUUAUUUCUGUAAAAUUUGUUUAGAAGUACGUUUUUGCAUUAUUCAUAUGCUUCCCAGAGAAGCUCAUUUAGUUAGAAAAUAAGGCAAGUUUUGAAGCCUGCUAAAUGAAGAGACUUAAGAAAGCUUAAGGUACGCUUGCUUGUCUUUAAAUCUUCAAUAUGAAGGACUAUUAAUUCCAAGAUUAAAAGUUCAUAUAUAGGCUAAAGAUGUAACUAGGCCAUUUGUAUUUGUAUUCCCUUUUAUUUCCAAAAUAAAAUGAAAAAUCUUUUUUUAAUAAUUUCAUCCCUAUUUAUAGUUUUUAUAUUAAUUUGUUUUUCUUAUCCAAGUAAAGAUGUCAAUAGGAAUUGCAUUAGUCCAAGGCCUUUUUCAUAAACUGAGCCUCUUUUCAAUUAUUUCAAUGGGACAGGAACUAGGAUAGAUGUGAUUCCUGCAUUUUUUUACCUUAAAUCUGCCUUUGUUUCUAAAGGUAGAUCAUCUUGAAUAUUUGCUUAAAAUUGCUAGUGAUUUCAUUACCAAGUUACUUGAAAAAAUGUUCUAUAUGCAUUUAAUUCUGAAAUCAGUCUACCAAGGGGCUGCUAGUAUAUGUCAGACAUGAAAACUAUUUUAAAGCUGACUUUGUUGCCUUAUCUUGAAAAGAAUCUAGAUAGGUGCUUUUAACUGGGGUAUUAACUUUUUUAGAAUGACACAGCUGAACAGUGUUAAUAAUAGUGUGUCAAGAUUGCAAAGUCGACAUACUCAUUUGGUUUAAGCAGGAAUCCUAGAAGCAAAUGGAUGGGGAUAAGAAUAGGUCAUUUUCUAUUCACCAUCCUUUACUAUUAAGGGAAAGGAAAAGAACACUAGCUAAGGAAGGGAAAGGGAAGUGAUAUCAUAAAAGUAGCAACCUUCAUUUUACAUUCUGUCUGUUUUUCUUUUUUUGCUUUGUUUUGUUUGUGCUAAUUUGGGAAUUGUGUACUCCGAAACAAGUAGAAAAGUGCUGUUUGAGGGAUUUUAUUAAAUCUUUUUUUAAUGGAAUGUGGUACAAAUUGUUCAUGUUACCAAAGCAAUAUUUCCCUGGAAUUUAAUUCAAAGUUUGUGGCAUACAACCUGAGCCUUUUCUUAUAUAAGACAAGAAUAUGUUCACAUCUUGGUAUGUGGCCAUAUUUAUAGAAUGCUGAACUCAAUGUGCAAGUUGUACUGUAUGCAGUUUUGUAAAUAAGUGAAAAUAAUUUGUUGUACUUUUUAUUCAAUUCUGUAUAGAUUAUAAAAUUAUUUUUAUUAAAUAAAUAUUUUACAGUAUAUUUUCUCUUUUUAAUCAAAA'

normal_mrna_slc19a2

'AGAGGCGUCUGUAGGGUAAAGCUGGGGGUUCUGUAGCCGGAGGCGGCGGCGAGUCCAGAACGUCCUGGCCUUACAGGGAGAAGGCGUCACUCGCGGUUACAAGUGCCUGACCCUCACUCCAGUUGGCGGAGGAGGAGAAGGAAGGGGCCGGGCCGGGUCCCCUCCCCUCGCGCCCCGGAUGGAUGUGCCCGGCCCGGUGUCUCGGCGGGCGGCGGCGGCGGCGGCCACUGUGCUCCUGCGGACCGCUCGGGUCCGUCGCGAAUGCUGGUUCUUGCCGACCGCGCUGCUCUGCGCCUACGGCUUCUUCGCCAGCCUCAGGCCGUCCGAGCCCUUCCUGACCCCGUACCUGCUGGGGCCGGACAAGAACCUGACCGAGAGGGAGGUCUUCAAUGAAAUUUAUCCAGUAUGGACUUACUCUUACCUGGUGCUACUGUUUCCUGUGUUCCUUGCCACAGACUACCUCCGUUAUAAACCUGUUGUUCUACUGCAGGGGCUCAGCCUUAUUGUUACAUGGUUUAUGCUGCUCUAUGCCCAGGGACUGCUGGCCAUUCAAUUUCUAGAAUUUUUUUAUGGCAUCGCCACAGCCACUGAAAUUGCCUAUUACUCUUAUAUCUACAGUGUGGUGGACCUGGGCAUGUACCAGAAAGUCACAAGUUACUGUCGAAGUGCCACUUUGGUGGGCUUUACAGUGGGCUCUGUCCUAGGGCAAAUCCUUGUCUCAGUGGCAGGCUGGUCGCUGUUCAGCCUGAAUGUCAUCUCUCUUACCUGUGUUUCAGUGGCUUUUGCUGUGGCCUGGUUUUUACCUAUGCCACAGAAGAGCCUCUUCUUUCACCACAUUCCUUCUACCUGCCAGAGAGUGAAUGGCAUCAAGGUACAAAAUGGUGGCAUUGUUACUGACACCCCAGCUUCUAACCACCUUCCUGGCUGGGAGGACAUUGAGUCAAAAAUCCCUCUAAAUAUGGAGGAGCCUCCCGUGGAGGAACCGGAACCCAAGCCAGACCGUCUCCUUGUAUUGAAAGUACUAUGGAAUGAUUUCCUGAUGUGCUACUCCUCUCGCCCUCUUCUCUGCUGGUCUGUGUGGUGGGCCCUCUCUACCUGUGGCUAUUUUCAAGUUGUGAACUACACACAGGGCCUGUGGGAGAAAGUGAUGCCUUCUCGCUAUGCUGCUAUCUAUAAUGGUGGCGUGGAGGCCGUUUCAACCUUACUGGGUGCUGUUGCUGUGUUUGCAGUUGGUUAUAUAAAAAUAUCCUGGUCAACUUGGGGAGAAAUGACAUUAUCUCUCUUUUCUCUCCUGAUUGCUGCUGCAGUGUAUAUCAUGGACACUGUGGGUAACAUUUGGGUGUGCUAUGCAUCCUAUGUUGUCUUCAGAAUCAUCUACAUGUUACUCAUCACGAUAGCAACUUUUCAAAUUGCUGCAAACCUCAGCAUGGAACGCUAUGCCCUAGUAUUUGGUGUAAAUACCUUCAUUGCCCUGGCACUGCAGACGCUGCUCACUCUAAUUGUGGUAGAUGCCAGUGGCCUUGGAUUAGAAAUUACCACUCAGUUUUUGAUCUAUGCCAGUUAUUUUGCACUCAUCGCUGUGGUUUUCCUGGCCAGUGGUGCAGUCAGUGUUAUGAAGAAAUGUAGAAAGCUGGAAGAUCCACAAUCAAGUUCUCAAGUAACCACUUCAUAAUAUACUGCUGAAGGGCUUCUUCUUAUAGCAAGAACUCUGCACAGCAACUGCCUGGAUGUGUUUGAUUUUUUAAAGCGUAGACAUAUAUUUAUGAAUGUGCAUUUCUUGACUUCACAGCAGCCACUUGACUAAUACCUUGUGUUCCGGGAAUAACAUGAUACUAUUCAGAGGAGCCAGAAGUAAAGUUUAUUUCAUGGAUUAUUUAUGAGAGCUAAUUUAAGGAUGACUUUUUUUCUGAUUCAAAAGUGAACUUGAUUUUAAAAACCAGUCAAGAGCAAUCAAAGCAGCACAUGGUGUUGUAUACUUCAUUAGCAAGUGAGUUUGGUGUUUUAUAGGUCACAUAUGUCUGUAUCUACUUAGCCAGAUGCUUGGCCUGGUGGGACCAGGGCUCCACAGAGGCCACAAAAUGUUGCAAGUCAUGAUGGAUGGAAAUAUGUUCUAACAGCAUCUGCCUCUAUUCAAUUUAAUUCUUAUUUCUGUGUUACUCAUGUACAUUGGUCUUUCUACAUAGUUAUUCUAUCACUGGCAAUAUUUGUUCUGGUUUAGUGUUCUGUAUUUUAAGGUGUACGUAUCAUUUCUAAUUUUAAGUUAUUUUAAAAAAAUUCAUCAUAUGAAUGUUCUUGGUUCCCAUUGUGACGAUUAUUUAUUUCUGUAAAAUUUGUUUAGAAGUACGUUUUUGCAUUAUUCAUAUGCUUCCCAGAGAAGCUCAUUUAGUUAGAAAAUAAGGCAAGUUUUGAAGCCUGCUAAAUGAAGAGACUUAAGAAAGCUUAAGGUACGCUUGCUUGUCUUUAAAUCUUCAAUAUGAAGGACUAUUAAUUCCAAGAUUAAAAGUUCAUAUAUAGGCUAAAGAUGUAACUAGGCCAUUUGUAUUUGUAUUCCCUUUUAUUUCCAAAAUAAAAUGAAAAAUCUUUUUUUAAUAAUUUCAUCCCUAUUUAUAGUUUUUAUAUUAAUUUGUUUUUCUUAUCCAAGUAAAGAUGUCAAUAGGAAUUGCAUUAGUCCAAGGCCUUUUUCAUAAACUGAGCCUCUUUUCAAUUAUUUCAAUGGGACAGGAACUAGGAUAGAUGUGAUUCCUGCAUUUUUUUACCUUAAAUCUGCCUUUGUUUCUAAAGGUAGAUCAUCUUGAAUAUUUGCUUAAAAUUGCUAGUGAUUUCAUUACCAAGUUACUUGAAAAAAUGUUCUAUAUGCAUUUAAUUCUGAAAUCAGUCUACCAAGGGGCUGCUAGUAUAUGUCAGACAUGAAAACUAUUUUAAAGCUGACUUUGUUGCCUUAUCUUGAAAAGAAUCUAGAUAGGUGCUUUUAACUGGGGUAUUAACUUUUUUAGAAUGACACAGCUGAACAGUGUUAAUAAUAGUGUGUCAAGAUUGCAAAGUCGACAUACUCAUUUGGUUUAAGCAGGAAUCCUAGAAGCAAAUGGAUGGGGAUAAGAAUAGGUCAUUUUCUAUUCACCAUCCUUUACUAUUAAGGGAAAGGAAAAGAACACUAGCUAAGGAAGGGAAAGGGAAGUGAUAUCAUAAAAGUAGCAACCUUCAUUUUACAUUCUGUCUGUUUUUCUUUUUUUGCUUUGUUUUGUUUGUGCUAAUUUGGGAAUUGUGUACUCCGAAACAAGUAGAAAAGUGCUGUUUGAGGGAUUUUAUUAAAUCUUUUUUUAAUGGAAUGUGGUACAAAUUGUUCAUGUUACCAAAGCAAUAUUUCCCUGGAAUUUAAUUCAAAGUUUGUGGCAUACAACCUGAGCCUUUUCUUAUAUAAGACAAGAAUAUGUUCACAUCUUGGUAUGUGGCCAUAUUUAUAGAAUGCUGAACUCAAUGUGCAAGUUGUACUGUAUGCAGUUUUGUAAAUAAGUGAAAAUAAUUUGUUGUACUUUUUAUUCAAUUCUGUAUAGAUUAUAAAAUUAUUUUUAUUAAAUAAAUAUUUUACAGUAUAUUUUCUCUUUUUAAUCAAAA'

In [66]:
dna_seq = """GACGGATCGGGAGATCTCCCGATCCCCTATGGTGCACTCTCAGTACAATCTGCTCTGATGCCGCATAGTTAAGCCAGTATCTGCTCCCTGCTTGTGTGTTGGAGGTCGCTGAGTAGTGCGCGAGCAAAATTTAAGCTACAACAAGGCAAGGCTTGACCGACAATTGCATGAAGAATCTGCTTAGGGTTAGGCGTTTTGCGCTGCTTCGCGATGTACGGGCCAGATATACGCGTTGACATTGATTATTGACTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGCCCAACGACCCCCGCCCATTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCCATTGACGTCAATGGGTGGAGTATTTACGGTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCCCCTATTGACGTCAATGACGGTAAATGGCCCGCCTGGCATTATGCCCAGTACATGACCTTATGGGACTTTCCTACTTGGCAGTACATCTACGTATTAGTCATCGCTATTACCATGGTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTGACTCACGGGGATTTCCAAGTCTCCACCCCATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCAAAATGTCGTAACAACTCCGCCCCATTGACGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCTCTCTGGCTAACTAGAGAACCCACTGCTTACTGGCTTATCGAAATTAATACGACTCACTATAGGGAGACCCAAGCTGGCTAGCGTTTAAACTTAAGCTTGCCACCATGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCACGGCATGGACGAGCTGTACAAGATGGATGTGCCCGGCCCGGTGTCTCGGCGGGCGGCGGCGGCGGCGGCCACTGTGCTCCTGCGGACCGCTCGGGTCCGTCGCGAATGCTGGTTCTTGCCGACCGCGCTGCTCTGCGCCTACGGCTTCTTCGCCAGCCTCAGGCCGTCCGAGCCCTTCCTGACCCAGTACCTGCTGGGGCCGGACAAGAACCTGACCGAGAGGGAGGTCTTCAATGAAATTTATCCAGTATGGACTTACTCTTACCTGGTGCTACTGTTTCCTGTGTTCCTTGCCACAGACTACCTCCGTTATAAACCTGTTGTTCTACTGCAGGGGCTCAGCCTTATTGTTACATGGTTTATGCTGCTCTATGCCCAGGGACTGCTGGCCATTCAATTTCTAGAATTTTTTTATGGCATCGCCACAGCCACTGAAATTGCCTATTACTCTTATATCTACAGTGTGGTGGACCTGGGCATGTACCAGAAAGTCACAAGTTACTGTCGAAGTGCCACTTTGGTGGGCTTTACAGTGGGCTCTGTCCTAGGGCAAATCCTTGTCTCAGTGGCAGGCTGGTCGCTGTTCAGCCTGAATGTCATCTCTCTTACCTGTGTTTCAGTGGCTTTTGCTGTGGCCTGGTTTTTACCTATGCCACAGAAGAGCCTCTTCTTTCACCACATTCCTTCTACCTGCCAGAGAGTGAATGGCATCAAGGTACAAAATGGTGGCATTGTTACTGACACCCCAGCTTCTAACCACCTTCCTGGCTGGGAGGACATTGAGTCAAAAATCCCTCTAAATATGGAGGAGCCTCCCGTGGAGGAACCGGAACCCAAGCCAGACCGTCTCCTTGTATTGAAAGTACTATGGAATGATTTCCTGATGTGCTACTCCTCTCGCCCTCTTCTCTGCTGGTCTGTGTGGTGGGCCCTCTCTACCTGTGGCTATTTTCAAGTTGTGAACTACACACAGGGCCTGTGGGAGAAAGTGATGCCTTCTCGCTATGCTGCTATCTATAATGGTGGCGTGGAGGCCGTTTCAACCTTACTGGGTGCTGTTGCTGTGTTTGCAGTTGGTTATATAAAAATATCCTGGTCAACTTGGGGAGAAATGACATTATCTCTCTTTTCTCTCCTGATTGCTGCTGCAGTGTATATCATGGACACTGTGGGTAACATTTGGGTGTGCTATGCATCCTATGTTGTCTTCAGAATCATCTACATGTTACTCATCACGATAGCAACTTTTCAAATTGCTGCAAACCTCAGCATGGAACGCTATGCCCTAGTATTTGGTGTAAATACCTTCATTGCCCTGGCACTGCAGACGCTGCTCACTCTAATTGTGGTAGATGCCAGTGGCCTTGGATTAGAAATTACCACTCAGTTTTTGATCTATGCCAGTTATTTTGCACTCATCGCTGTGGTTTTCCTGGCCAGTGGTGCAGTCAGTGTTATGAAGAAATGTAGAAAGCTGGAAGATCCACAATCAAGTTCTCAAGTAACCACTTCATAAACCCGCTGATCAGCCTCGACTGTGCCTTCTAGTTGCCAGCCATCTGTTGTTTGCCCCTCCCCCGTGCCTTCCTTGACCCTGGAAGGTGCCACTCCCACTGTCCTTTCCTAATAAAATGAGGAAATTGCATCGCATTGTCTGAGTAGGTGTCATTCTATTCTGGGGGGTGGGGTGGGGCAGGACAGCAAGGGGGAGGATTGGGAAGACAATAGCAGGCATGCTGGGGATGCGGTGGGCTCTATGGCTTCTGAGGCGGAAAGAACCAGCTGGGGCTCTAGGGGGTATCCCCACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTAATTCTGTGGAATGTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAAAAGCTCCCGGGAGCTTGTATATCCATTTTCGGATCTGATCAAGAGACAGGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGAGCGGGACTCTGGGGTTCGAAATGACCGACCAAGCGACGCCCAACCTGCCATCACGAGATTTCGATTCCACCGCCGCCTTCTATGAAAGGTTGGGCTTCGGAATCGTTTTCCGGGACGCCGGCTGGATGATCCTCCAGCGCGGGGATCTCATGCTGGAGTTCTTCGCCCACCCCAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGTATACCGTCGACCTCTAGCTAGAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGCCTAATGAGTGAGCTAACTCACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTC"""

In [67]:
start = 'ATGGATGTGCCC'
start_len = len(start)

start_index = dna_seq.find(start)
if start_index != -1:
    print(f"Found start codon at position: {start_index}")
    # Extract sequence from start codon onwards
    sequence_from_start = dna_seq[start_index:]
else:
    print("Start codon not found")

Found start codon at position: 1636

In [68]:
sequence_from_start

'ATGGATGTGCCCGGCCCGGTGTCTCGGCGGGCGGCGGCGGCGGCGGCCACTGTGCTCCTGCGGACCGCTCGGGTCCGTCGCGAATGCTGGTTCTTGCCGACCGCGCTGCTCTGCGCCTACGGCTTCTTCGCCAGCCTCAGGCCGTCCGAGCCCTTCCTGACCCAGTACCTGCTGGGGCCGGACAAGAACCTGACCGAGAGGGAGGTCTTCAATGAAATTTATCCAGTATGGACTTACTCTTACCTGGTGCTACTGTTTCCTGTGTTCCTTGCCACAGACTACCTCCGTTATAAACCTGTTGTTCTACTGCAGGGGCTCAGCCTTATTGTTACATGGTTTATGCTGCTCTATGCCCAGGGACTGCTGGCCATTCAATTTCTAGAATTTTTTTATGGCATCGCCACAGCCACTGAAATTGCCTATTACTCTTATATCTACAGTGTGGTGGACCTGGGCATGTACCAGAAAGTCACAAGTTACTGTCGAAGTGCCACTTTGGTGGGCTTTACAGTGGGCTCTGTCCTAGGGCAAATCCTTGTCTCAGTGGCAGGCTGGTCGCTGTTCAGCCTGAATGTCATCTCTCTTACCTGTGTTTCAGTGGCTTTTGCTGTGGCCTGGTTTTTACCTATGCCACAGAAGAGCCTCTTCTTTCACCACATTCCTTCTACCTGCCAGAGAGTGAATGGCATCAAGGTACAAAATGGTGGCATTGTTACTGACACCCCAGCTTCTAACCACCTTCCTGGCTGGGAGGACATTGAGTCAAAAATCCCTCTAAATATGGAGGAGCCTCCCGTGGAGGAACCGGAACCCAAGCCAGACCGTCTCCTTGTATTGAAAGTACTATGGAATGATTTCCTGATGTGCTACTCCTCTCGCCCTCTTCTCTGCTGGTCTGTGTGGTGGGCCCTCTCTACCTGTGGCTATTTTCAAGTTGTGAACTACACACAGGGCCTGTGGGAGAAAGTGATGCCTTCTCGCTATGCTGCTATCTATAATGGTGGCGTGGAGGCCGTTTCAACCTTACTGGGTGCTGTTGCTGTGTTTGCAGTTGGTTATATAAAAATATCCTGGTCAACTTGGGGAGAAATGACATTATCTCTCTTTTCTCTCCTGATTGCTGCTGCAGTGTATATCATGGACACTGTGGGTAACATTTGGGTGTGCTATGCATCCTATGTTGTCTTCAGAATCATCTACATGTTACTCATCACGATAGCAACTTTTCAAATTGCTGCAAACCTCAGCATGGAACGCTATGCCCTAGTATTTGGTGTAAATACCTTCATTGCCCTGGCACTGCAGACGCTGCTCACTCTAATTGTGGTAGATGCCAGTGGCCTTGGATTAGAAATTACCACTCAGTTTTTGATCTATGCCAGTTATTTTGCACTCATCGCTGTGGTTTTCCTGGCCAGTGGTGCAGTCAGTGTTATGAAGAAATGTAGAAAGCTGGAAGATCCACAATCAAGTTCTCAAGTAACCACTTCATAAACCCGCTGATCAGCCTCGACTGTGCCTTCTAGTTGCCAGCCATCTGTTGTTTGCCCCTCCCCCGTGCCTTCCTTGACCCTGGAAGGTGCCACTCCCACTGTCCTTTCCTAATAAAATGAGGAAATTGCATCGCATTGTCTGAGTAGGTGTCATTCTATTCTGGGGGGTGGGGTGGGGCAGGACAGCAAGGGGGAGGATTGGGAAGACAATAGCAGGCATGCTGGGGATGCGGTGGGCTCTATGGCTTCTGAGGCGGAAAGAACCAGCTGGGGCTCTAGGGGGTATCCCCACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTAATTCTGTGGAATGTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAAAAGCTCCCGGGAGCTTGTATATCCATTTTCGGATCTGATCAAGAGACAGGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGAGCGGGACTCTGGGGTTCGAAATGACCGACCAAGCGACGCCCAACCTGCCATCACGAGATTTCGATTCCACCGCCGCCTTCTATGAAAGGTTGGGCTTCGGAATCGTTTTCCGGGACGCCGGCTGGATGATCCTCCAGCGCGGGGATCTCATGCTGGAGTTCTTCGCCCACCCCAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGTATACCGTCGACCTCTAGCTAGAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGCCTAATGAGTGAGCTAACTCACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTC'

In [69]:
from Bio.Seq import Seq

protien = Seq(sequence_from_start).translate(to_stop=False)
print(protien)

MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASLRPSEPFLTQYLLGPDKNLTEREVFNEIYPVWTYSYLVLLFPVFLATDYLRYKPVVLLQGLSLIVTWFMLLYAQGLLAIQFLEFFYGIATATEIAYYSYIYSVVDLGMYQKVTSYCRSATLVGFTVGSVLGQILVSVAGWSLFSLNVISLTCVSVAFAVAWFLPMPQKSLFFHHIPSTCQRVNGIKVQNGGIVTDTPASNHLPGWEDIESKIPLNMEEPPVEEPEPKPDRLLVLKVLWNDFLMCYSSRPLLCWSVWWALSTCGYFQVVNYTQGLWEKVMPSRYAAIYNGGVEAVSTLLGAVAVFAVGYIKISWSTWGEMTLSLFSLLIAAAVYIMDTVGNIWVCYASYVVFRIIYMLLITIATFQIAANLSMERYALVFGVNTFIALALQTLLTLIVVDASGLGLEITTQFLIYASYFALIAVVFLASGAVSVMKKCRKLEDPQSSSQVTTS*TR*SASTVPSSCQPSVVCPSPVPSLTLEGATPTVLS**NEEIASHCLSRCHSILGGGVGQDSKGEDWEDNSRHAGDAVGSMASEAERTSWGSRGYPHAPCSGALSAAGVVVTRSVTATLASALAPAPFAFFPSFLATFAGFPRQALNRGLPLGFRFSALRHLDPKKLD*GDGSRSGPSP**TVFRPLTLESTFFNSGLLFQTGTTLNPISVYSFDL*GILPISAYWLKNELI*QKFNAN*FCGMCVS*GVESPQAPQQAEVCKACISISQQPGVESPQAPQQAEVCKACISISQQP*SRP*LRPSRP*LRPVPPILRPMAD*FFLFMQRPRPPLPLSYSRSSEEAFLEA*AFAKSSRELVYPFSDLIKRQDEDRFA*LNKMDCTQVLRPLGWRGYSAMTGHNRQSAALMPPCSGCQRRGARFFLSRPTCPVP*MNCRTRQRGYRGWPRRAFLAQLCSTLSLKREGTGCYWAKCRGRISCHLTLLLPRKYPSWLMQCGGCIRLIRLPAHSTTKRNIASSEHVLGWKPVLSIRMIWTKSIRGSRQPNCSPGSRRACPTARISS*PMAMPACRISWWKMAAFLDSSTVAGWVWRTAIRT*RWLPVILLKSLAANGLTASSCFTVSPLPIRSASPSIAFLTSSSERDSGVRNDRPSDAQPAITRFRFHRRLL*KVGLRNRFPGRRLDDPPARGSHAGVLRPPQLVYCSL*WLQIKQ*HHKFHK*SIFFTAF*LWFVQTHQCILSCLYTVDL*LELGVIMVIAVSCVKLLSAHNSTQHTSRKHKV*SLGCLMSELTHINCVALTARFPVGKPVVPAALMNRPTRGERRFAYWALFRFLAH*LAALGRSAAASGISSLKGGNTVIHRIRG*RRKEHVSKRPAKGQEP*KGRVAGVFP*APPP*RASQKSTLKSEVAKPDRTIKIPGVSPWKLPRALSCSDPAAYRIPVRLSPFGKRGAFS*LTL*VSQFGVGRSLQAGLCARTPRSARPLRLIR*LSS*VQPGKTRLIATGSSHW*QD*QSEVCRRCYRVLEVVA*LRLH*KNSIWYLRSAEASYLRKKSW*LLIRQTNHRW*RWFFCLQAADYAQKKRISRRSFDLFYGV*RSVERKLTLRDFGHEIIKKDLHLDPFKLKMKF*INLKYI*VNLV*QLPMLNQ*GTYLSDLSISFIHSCLTPRRVDNYDTGGLTIWPQCCNDTARPTLTGSRFISNKPASRKGRAQKWSCNFIRLHPVY*LLPGS*SK*FAS**FAQRCCHCYRHRGVTLVVWYGFIQLRFPTIKASYMIPHVVQKSG*LLRSSDRCQK*VGRSVITHGYGSTA*FSYCHAIRKMLFCDW*VLNQVILRIVYAATELLLPGVNTG*YRAT*QNFKSAHHWKTFFGAKTLKDLTAVEIQFDVTHSCTQLIFSIFYFHQRFWVSKNRKAKCRKKGNKGDTEMLNTHTLPFSILLKHLSGLLSHERIHI*MYLEK*TNRGSAHISPKSAT*R